---
- name: Install Jenkins and Terraform on CentOS
  hosts: localhost
  become: true
  tasks:
    - name: Install YUM Utils
      yum:  
        name: yum-utils        
        state: present
    
    - name: Install Java
      yum:
        name: java-latest-openjdk-devel
        state: present

    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        gpgcheck: no
        description: Jenkins
        baseurl: http://pkg.jenkins.io/redhat-stable
        state: present
    
    - name: Add Terraform repository
      yum_repository:
        name: terraform
        gpgcheck: no
        description: Terraform
        baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable 
        state: present

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Install Terraform
      yum:
        name: terraform
        state: present
